### ISSUE TITLE
[Bug] 将转换保存至 Database Repository（MySQL），再次打开时报错 java.lang.NumberFormatException: null

### ISSUE THREAD

**Issue by WuMenglong** [StarRocks/starrocks-connector-for-kettle#6]
在 Kettle 9.4 中使用 starrocks-connector-for-kettle 插件创建转换，然后将转换保存至使用 MySQL 5.7.33 创建的 Database Repository，转换可正常保存至仓库，但当再次从仓库打开该转换时，会报错 NumberFormatException：

![image](https://github.com/StarRocks/starrocks-connector-for-kettle/assets/90299197/e325c83a-1632-4b9c-a02d-7e78aa1b3651)

完整异常信息如下：

```shell
java.lang.reflect.InvocationTargetException: 错误加载转换
	at org.pentaho.di.ui.trans.dialog.TransLoadProgressDialog$1.run(TransLoadProgressDialog.java:123)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: org.pentaho.di.core.exception.KettleException: 
一个数据库错误发生在从资源库文件读取转换时

Unexpected error reading step information from the repository.
null


	at org.pentaho.di.repository.kdr.delegates.KettleDatabaseRepositoryTransDelegate.loadTransformation(KettleDatabaseRepositoryTransDelegate.java:674)
	at org.pentaho.di.repository.kdr.KettleDatabaseRepository.loadTransformation(KettleDatabaseRepository.java:350)
	at org.pentaho.di.repository.kdr.KettleDatabaseRepository.loadTransformation(KettleDatabaseRepository.java:2057)
	at org.pentaho.di.ui.trans.dialog.TransLoadProgressDialog$1.run(TransLoadProgressDialog.java:103)
	... 1 more
Caused by: org.pentaho.di.core.exception.KettleException: 
Unexpected error reading step information from the repository.
null

	at org.pentaho.di.trans.steps.starrockskettleconnector.StarRocksKettleConnectorMeta.readRep(StarRocksKettleConnectorMeta.java:711)
	at org.pentaho.di.repository.kdr.delegates.KettleDatabaseRepositoryStepDelegate.loadStepMeta(KettleDatabaseRepositoryStepDelegate.java:175)
	at org.pentaho.di.repository.kdr.delegates.KettleDatabaseRepositoryTransDelegate.loadTransformation(KettleDatabaseRepositoryTransDelegate.java:540)
	... 4 more
Caused by: java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.valueOf(Long.java:803)
	at org.pentaho.di.trans.steps.starrockskettleconnector.StarRocksKettleConnectorMeta.readRep(StarRocksKettleConnectorMeta.java:685)
	... 6 more
```

**Comment by winnie655535** [comment]
遇到了通样的问题，请问当时解决了吗？如何处理的？
